version: 2.1

orbs:
  silta: silta/silta@0.1

executors:
  cicd16:
    docker:
      - image: wunderio/silta-cicd:circleci-php8.1-node16-composer2

workflows:
  version: 2
  commit:
    jobs:
      # silta/frontend-build-deploy is defined here https://github.com/wunderio/silta-circleci/blob/master/orb/jobs/%40frontend.yml
      # &build-deploy is a yaml anchor, so we can reference it later
      - silta/frontend-build-deploy: &frontend-build-deploy
          name: Silta build & deploy
          executor: cicd16
          context: silta_dev
          silta_config: silta/silta.yml
          codebase-build:
            # npm-install-build command is defined here https://github.com/wunderio/silta-circleci/blob/master/orb/commands/@npm.yml
            - silta/npm-install-build
          filters:
            branches:
              ignore:
                - production
                - /dependabot\/.*/

      - silta/frontend-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *frontend-build-deploy
          name: Silta build & deploy production
          executor: cicd16
          context: silta_finland
          silta_config: silta/silta.yml,silta/silta-prod.yml
          filters:
            branches:
              only: production

      - silta/frontend-build-deploy:
          <<: *frontend-build-deploy
          name: Build Dependabot
          executor: cicd16
          context: silta_dev
          skip-deployment: true
          filters:
            branches:
              only: /dependabot\/.*/
