version: 2.1

orbs:
  silta: silta/silta@0.1

workflows:
  version: 2
  commit:
    jobs:
      # silta/frontend-build-deploy is defined here https://github.com/wunderio/silta-circleci/blob/master/orb/jobs/%40frontend.yml
      # &build-deploy is a yaml anchor, so we can reference it later
      - silta/frontend-build-deploy: &frontend-build-deploy
          name: Silta build & deploy
          context: silta_dev
          silta_config: silta/silta.yml
          codebase-build:
            # npm-install-build command is defined here https://github.com/wunderio/silta-circleci/blob/master/orb/commands/@npm.yml
            - silta/npm-install-build
          filters:
            branches:
              ignore: production

      - silta/frontend-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *frontend-build-deploy
          name: Silta build & deploy production
          context: silta_finland
          silta_config: silta/silta.yml,silta/silta-prod.yml
          filters:
            branches:
              only: production
