version: 2.1

orbs:
  silta: silta/silta@0.1

images:
  - &node
    image: circleci/node:12.16.1-browsers

executors:
  node:
    docker:
      - *node

jobs:
  install:
    executor: node
    steps:
      - checkout:
          path: ~/project/build_path
      - restore_cache:
          keys:
            - v1-circleci-nextjs-dependencies-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install Dependencies
          command: cd build_path && npm ci
      - save_cache:
          key: v1-circleci-nextjs-dependencies-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.npm
            - ~/.cache
  jest:
    docker:
      - image: circleci/node:12.16.1-browsers
    resource_class: large
    steps:
      - checkout:
          path: ~/project/build_path
      - restore_cache:
          key: v1-circleci-nextjs-dependencies-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install dependencies
          command: cd build_path && npm ci
      - run:
          name: Jest tests
          command: cd build_path && npm run test:jest
      - store_artifacts:
          path: ~/project/build_path/tests/jest/snapshots/diff_output
          destination: tests/jest/snapshots/diff_output
      - run:
          name: Update image snapshots when tests fails
          command: cd build_path && npm run test:jest:update
          when: on_fail
      - store_artifacts:
          path: ~/project/build_path/tests/jest/snapshots/current_output
          destination: tests/jest/snapshots/current_output
  cypress:
    docker:
      - image: circleci/node:12.16.1-browsers
    resource_class: large
    steps:
      - checkout:
          path: ~/project/build_path
      - restore_cache:
          key: v1-circleci-nextjs-dependencies-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install dependencies
          command: cd build_path && npm ci
      - run:
          name: Build application
          command: cd build_path && npm run build
      - run:
          name: Run application
          command: cd build_path && npm run start
          background: true
      - run:
          name: Cypress tests
          command: cd build_path && npm run test:cypress:run
      - store_artifacts:
          path: ~/project/build_path/cypress/screenshots
          destination: cypress/screenshots
      - store_artifacts:
          path: ~/project/build_path/cypress/snapshots/diff_output
          destination: cypress/snapshots/diff_output
      - run:
          name: Update image snapshots when tests fails
          command: cd build_path && npm run test:cypress:run:update
          when: on_fail
      - store_artifacts:
          path: ~/project/build_path/cypress/snapshots/current_output
          destination: cypress/snapshots/current_output
          
workflows:
  version: 2
  commit:
    jobs:
      - install
      - jest:
          requires:
            - install
      - cypress:
          requires:
            - install
      # silta/frontend-build-deploy is defined here https://github.com/wunderio/silta-circleci/blob/master/orb/jobs/%40frontend.yml
      # &build-deploy is a yaml anchor, so we can reference it later
      - silta/frontend-build-deploy: &frontend-build-deploy
          name: Silta build & deploy
          context: silta_dev
          silta_config: silta/silta.yml
          codebase-build:
            # npm-install-build command is defined here https://github.com/wunderio/silta-circleci/blob/master/orb/commands/@npm.yml
            - silta/npm-install-build
          filters:
            branches:
              ignore: production
      - silta/frontend-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *frontend-build-deploy
          name: Silta build & deploy production
          context: silta_finland
          silta_config: silta/silta.yml,silta/silta-prod.yml
          filters:
            branches:
              only: production
